# src/main/resources/application.properties
# データベース接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/typing_words
spring.datasource.username=root
spring.datasource.password=musako63369
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update  # スキーマ自動更新
spring.jpa.show-sql=true  # SQLログを表示
spring.jpa.properties.hibernate.format_sql=true

# サーバーポート設定（デフォルトは8080）
server.port=8080